### ISSUE TITLE
check this repo!

### ISSUE THREAD

**Issue by mudongliang** [BartVandewoestyne/Cpp_Primer#1]
https://github.com/Mooophy/Cpp-Primer
Check this repo and see the differences to decide to write yours or contribute to this !!!

**Comment by BartVandewoestyne** [comment]
I am aware of the existence of Mooophy's repository.  I still prefer to have my own repository because this is mainly an exercise for myself.  I want to make the exercises personally, and by sharing my solutions I hope to get comments and suggestions from the community so I can learn from it.  Thanks for your understanding.
